name: noon_reader
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^3.0.1
  file_picker: ^5.0.1
  hooks_riverpod: ^1.0.1
  settings_ui: ^2.0.2
  freezed_annotation: ^2.1.0
  modal_bottom_sheet: ^2.0.0
  json_annotation: ^4.0.1
  logger: ^1.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.18.5+1
  scrollable_positioned_list: ^0.3.2
  dartz: ^0.10.1
  flutter_charset_detector: ^1.0.2
  easy_debounce: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter

  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/